# Generated by Django 3.1.4 on 2020-12-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=50, verbose_name='用户id')),
                ('user_name', models.CharField(max_length=50, verbose_name='用户名')),
                ('chat_data', models.CharField(max_length=999, verbose_name='聊天数据')),
                ('chat_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '聊天数据',
                'verbose_name_plural': '聊天数据',
            },
        ),
    ]
